### ISSUE TITLE
add LICENSE file

### ISSUE THREAD

**Issue by ongardie** [nicehoplite/GlucoRAFT#1]
The README says this is MIT. However, it links to a LICENSE file that doesn't exist.

If you create a file in the right format, GitHub will recognize that and display it in the UI. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by nicehoplite** [comment]
Thanks for pointing this out! I have created the license file and link also works now.
